# CMake generated Testfile for 
# Source directory: /home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests
# Build directory: /home/ehassani/projects/private-combblas/CombBLAS/_build/ReleaseTests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[GenMMWrite_Test]=] "/sw/eb/sw/impi/2021.13.0-intel-compilers-2024.2.0/mpi/2021.13/bin/mpiexec" "-n" "4" "/home/ehassani/projects/private-combblas/CombBLAS/_build/ReleaseTests/GenWrMat" "20" "16" "1" "scale20_ef16_symmetric.mtx")
set_tests_properties([=[GenMMWrite_Test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;43;ADD_TEST;/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;0;")
add_test([=[Multiplication_Test]=] "/sw/eb/sw/impi/2021.13.0-intel-compilers-2024.2.0/mpi/2021.13/bin/mpiexec" "-n" "4" "/home/ehassani/projects/private-combblas/CombBLAS/_build/ReleaseTests/MultTest" "../TESTDATA/rmat_scale16_A.mtx" "../TESTDATA/rmat_scale16_B.mtx" "../TESTDATA/rmat_scale16_productAB.mtx" "../TESTDATA/x_65536_halfdense.txt" "../TESTDATA/y_65536_halfdense.txt")
set_tests_properties([=[Multiplication_Test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;44;ADD_TEST;/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;0;")
add_test([=[SpGEMM3D_Test]=] "/sw/eb/sw/impi/2021.13.0-intel-compilers-2024.2.0/mpi/2021.13/bin/mpiexec" "-n" "16" "/home/ehassani/projects/private-combblas/CombBLAS/_build/ReleaseTests/SpGEMM3DTest" "../TESTDATA/rmat_scale16_A.mtx" "../TESTDATA/rmat_scale16_B.mtx" "../TESTDATA/rmat_scale16_productAB.mtx")
set_tests_properties([=[SpGEMM3D_Test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;52;ADD_TEST;/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;0;")
add_test([=[HashSpGEMMTest]=] "/sw/eb/sw/impi/2021.13.0-intel-compilers-2024.2.0/mpi/2021.13/bin/mpiexec" "-n" "1" "/home/ehassani/projects/private-combblas/CombBLAS/_build/ReleaseTests/HashSpGEMMTest" "../TESTDATA/rmat_scale16_A.mtx" "../TESTDATA/rmat_scale16_B.mtx" "../TESTDATA/rmat_scale16_productAB.mtx")
set_tests_properties([=[HashSpGEMMTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;55;ADD_TEST;/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;0;")
add_test([=[Reduction_Test]=] "/sw/eb/sw/impi/2021.13.0-intel-compilers-2024.2.0/mpi/2021.13/bin/mpiexec" "-n" "4" "/home/ehassani/projects/private-combblas/CombBLAS/_build/ReleaseTests/ReduceTest" "../TESTDATA/sprand10000" "../TESTDATA/sprand10000_sumcols" "../TESTDATA/sprand10000_sumrows")
set_tests_properties([=[Reduction_Test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;56;ADD_TEST;/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;0;")
add_test([=[Iterator_Test]=] "/sw/eb/sw/impi/2021.13.0-intel-compilers-2024.2.0/mpi/2021.13/bin/mpiexec" "-n" "4" "/home/ehassani/projects/private-combblas/CombBLAS/_build/ReleaseTests/IteratorTest" "../TESTDATA" "sprand10000")
set_tests_properties([=[Iterator_Test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;57;ADD_TEST;/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;0;")
add_test([=[Transpose_Test]=] "/sw/eb/sw/impi/2021.13.0-intel-compilers-2024.2.0/mpi/2021.13/bin/mpiexec" "-n" "4" "/home/ehassani/projects/private-combblas/CombBLAS/_build/ReleaseTests/TransposeTest" "../TESTDATA" "betwinput_scale16" "betwinput_transposed_scale16")
set_tests_properties([=[Transpose_Test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;58;ADD_TEST;/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;0;")
add_test([=[Local_SpDCCols_Transpose_Test]=] "/sw/eb/sw/impi/2021.13.0-intel-compilers-2024.2.0/mpi/2021.13/bin/mpiexec" "-n" "1" "/home/ehassani/projects/private-combblas/CombBLAS/_build/ReleaseTests/Local_SpDCCols_Transpose_Test" "10")
set_tests_properties([=[Local_SpDCCols_Transpose_Test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;59;ADD_TEST;/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;0;")
add_test([=[Indexing_Test]=] "/sw/eb/sw/impi/2021.13.0-intel-compilers-2024.2.0/mpi/2021.13/bin/mpiexec" "-n" "4" "/home/ehassani/projects/private-combblas/CombBLAS/_build/ReleaseTests/IndexingTest" "../TESTDATA" "B_100x100.txt" "B_10x30_Indexed.txt" "rand10outta100.txt" "rand30outta100.txt")
set_tests_properties([=[Indexing_Test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;60;ADD_TEST;/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;0;")
add_test([=[SpAsgn_Test]=] "/sw/eb/sw/impi/2021.13.0-intel-compilers-2024.2.0/mpi/2021.13/bin/mpiexec" "-n" "4" "/home/ehassani/projects/private-combblas/CombBLAS/_build/ReleaseTests/SpAsgnTest" "../TESTDATA" "A_100x100.txt" "A_with20x30hole.txt" "dense_20x30matrix.txt" "A_wdenseblocks.txt" "20outta100.txt" "30outta100.txt")
set_tests_properties([=[SpAsgn_Test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;61;ADD_TEST;/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;0;")
add_test([=[GalerkinNew_Test]=] "/sw/eb/sw/impi/2021.13.0-intel-compilers-2024.2.0/mpi/2021.13/bin/mpiexec" "-n" "4" "/home/ehassani/projects/private-combblas/CombBLAS/_build/ReleaseTests/GalerkinNew" "../TESTDATA/grid3d_k5.txt" "../TESTDATA/offdiag_grid3d_k5.txt" "../TESTDATA/diag_grid3d_k5.txt" "../TESTDATA/restrict_T_grid3d_k5.txt")
set_tests_properties([=[GalerkinNew_Test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;62;ADD_TEST;/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;0;")
add_test([=[FindSparse_Test]=] "/sw/eb/sw/impi/2021.13.0-intel-compilers-2024.2.0/mpi/2021.13/bin/mpiexec" "-n" "4" "/home/ehassani/projects/private-combblas/CombBLAS/_build/ReleaseTests/FindSparse" "../TESTDATA" "findmatrix.txt")
set_tests_properties([=[FindSparse_Test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;63;ADD_TEST;/home/ehassani/projects/private-combblas/CombBLAS/ReleaseTests/CMakeLists.txt;0;")
