# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.24)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS CombBLAS::Usortlib CombBLAS::GraphGenlib CombBLAS::CombBLAS)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target CombBLAS::Usortlib
add_library(CombBLAS::Usortlib STATIC IMPORTED)

set_target_properties(CombBLAS::Usortlib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/ehassani/projects/private-combblas/CombBLAS/usort/include"
  INTERFACE_LINK_LIBRARIES "MPI::MPI_CXX"
)

# Create imported target CombBLAS::GraphGenlib
add_library(CombBLAS::GraphGenlib STATIC IMPORTED)

set_target_properties(CombBLAS::GraphGenlib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/ehassani/projects/private-combblas/CombBLAS/graph500-1.2/generator/include"
)

# Create imported target CombBLAS::CombBLAS
add_library(CombBLAS::CombBLAS STATIC IMPORTED)

set_target_properties(CombBLAS::CombBLAS PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "THREADED"
  INTERFACE_INCLUDE_DIRECTORIES "/home/ehassani/projects/private-combblas/CombBLAS/include;/home/ehassani/projects/private-combblas/CombBLAS/psort-1.0/include"
  INTERFACE_LINK_LIBRARIES "MPI::MPI_CXX;OpenMP::OpenMP_CXX;CombBLAS::Usortlib;CombBLAS::GraphGenlib"
)

# Import target "CombBLAS::Usortlib" for configuration ""
set_property(TARGET CombBLAS::Usortlib APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(CombBLAS::Usortlib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/home/ehassani/projects/private-combblas/CombBLAS/_build/usort/libUsortlib.a"
  )

# Import target "CombBLAS::GraphGenlib" for configuration ""
set_property(TARGET CombBLAS::GraphGenlib APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(CombBLAS::GraphGenlib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/home/ehassani/projects/private-combblas/CombBLAS/_build/graph500-1.2/generator/libGraphGenlib.a"
  )

# Import target "CombBLAS::CombBLAS" for configuration ""
set_property(TARGET CombBLAS::CombBLAS APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(CombBLAS::CombBLAS PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C;CXX"
  IMPORTED_LOCATION_NOCONFIG "/home/ehassani/projects/private-combblas/CombBLAS/_build/libCombBLAS.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
